// Package remotemaintenancev3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package remotemaintenancev3

import (
	"time"
)

// Defines values for CommonTypeAsyncStatus.
const (
	CommonTypeAsyncStatusComplete   CommonTypeAsyncStatus = "Complete"
	CommonTypeAsyncStatusFail       CommonTypeAsyncStatus = "Fail"
	CommonTypeAsyncStatusInProgress CommonTypeAsyncStatus = "InProgress"
	CommonTypeAsyncStatusPending    CommonTypeAsyncStatus = "Pending"
)

// Defines values for CommonTypeNoReceivedTimestampAsyncStatus.
const (
	CommonTypeNoReceivedTimestampAsyncStatusComplete   CommonTypeNoReceivedTimestampAsyncStatus = "Complete"
	CommonTypeNoReceivedTimestampAsyncStatusFail       CommonTypeNoReceivedTimestampAsyncStatus = "Fail"
	CommonTypeNoReceivedTimestampAsyncStatusInProgress CommonTypeNoReceivedTimestampAsyncStatus = "InProgress"
	CommonTypeNoReceivedTimestampAsyncStatusPending    CommonTypeNoReceivedTimestampAsyncStatus = "Pending"
)

// Defines values for ResourceDataTypeAsyncStatus.
const (
	ResourceDataTypeAsyncStatusComplete   ResourceDataTypeAsyncStatus = "Complete"
	ResourceDataTypeAsyncStatusFail       ResourceDataTypeAsyncStatus = "Fail"
	ResourceDataTypeAsyncStatusInProgress ResourceDataTypeAsyncStatus = "InProgress"
	ResourceDataTypeAsyncStatusPending    ResourceDataTypeAsyncStatus = "Pending"
)

// Defines values for ValueDataTypeAsyncStatus.
const (
	ValueDataTypeAsyncStatusComplete   ValueDataTypeAsyncStatus = "Complete"
	ValueDataTypeAsyncStatusFail       ValueDataTypeAsyncStatus = "Fail"
	ValueDataTypeAsyncStatusInProgress ValueDataTypeAsyncStatus = "InProgress"
	ValueDataTypeAsyncStatusPending    ValueDataTypeAsyncStatus = "Pending"
)

// Defines values for VehicleDataReadoutRefreshDataTypeAsyncStatus.
const (
	VehicleDataReadoutRefreshDataTypeAsyncStatusComplete   VehicleDataReadoutRefreshDataTypeAsyncStatus = "Complete"
	VehicleDataReadoutRefreshDataTypeAsyncStatusFail       VehicleDataReadoutRefreshDataTypeAsyncStatus = "Fail"
	VehicleDataReadoutRefreshDataTypeAsyncStatusInProgress VehicleDataReadoutRefreshDataTypeAsyncStatus = "InProgress"
	VehicleDataReadoutRefreshDataTypeAsyncStatusPending    VehicleDataReadoutRefreshDataTypeAsyncStatus = "Pending"
)

// Defines values for WarningIndicatorReadoutDataItemStatus.
const (
	WarningIndicatorReadoutDataItemStatusSTATUSACTIVE            WarningIndicatorReadoutDataItemStatus = "STATUS_ACTIVE"
	WarningIndicatorReadoutDataItemStatusSTATUSACTIVEANDBLINKING WarningIndicatorReadoutDataItemStatus = "STATUS_ACTIVE_AND_BLINKING"
	WarningIndicatorReadoutDataItemStatusSTATUSNOTACTIVE         WarningIndicatorReadoutDataItemStatus = "STATUS_NOT_ACTIVE"
	WarningIndicatorReadoutDataItemStatusSTATUSUNDEFINED         WarningIndicatorReadoutDataItemStatus = "STATUS_UNDEFINED"
	WarningIndicatorReadoutDataItemStatusSTATUSUNKNOWN           WarningIndicatorReadoutDataItemStatus = "STATUS_UNKNOWN"
)

// Defines values for WarningIndicatorReadoutDataTypeAsyncStatus.
const (
	WarningIndicatorReadoutDataTypeAsyncStatusComplete   WarningIndicatorReadoutDataTypeAsyncStatus = "Complete"
	WarningIndicatorReadoutDataTypeAsyncStatusFail       WarningIndicatorReadoutDataTypeAsyncStatus = "Fail"
	WarningIndicatorReadoutDataTypeAsyncStatusInProgress WarningIndicatorReadoutDataTypeAsyncStatus = "InProgress"
	WarningIndicatorReadoutDataTypeAsyncStatusPending    WarningIndicatorReadoutDataTypeAsyncStatus = "Pending"
)

// CommonType defines model for CommonType.
type CommonType struct {
	// AsyncStatus Reflects the status of the readouts
	AsyncStatus CommonTypeAsyncStatus `json:"asyncStatus"`

	// ID Id unique for this readout.
	ID string `json:"id"`

	// MessageTimestamp Timestamp when this message was created.
	MessageTimestamp time.Time `json:"messageTimestamp,omitzero"`

	// ReceivedTimestamp Timestamp when the data in the message was received by the ExVe backend from the vehicle.
	ReceivedTimestamp time.Time `json:"receivedTimestamp,omitempty,omitzero"`

	// VehicleID The vehicle identifier of the extended vehicle, e.g VIN
	VehicleID string `json:"vehicleId"`
}

// CommonTypeAsyncStatus Reflects the status of the readouts
type CommonTypeAsyncStatus string

// CommonTypeNoReceivedTimestamp defines model for CommonTypeNoReceivedTimestamp.
type CommonTypeNoReceivedTimestamp struct {
	// AsyncStatus Reflects the status of the readouts
	AsyncStatus CommonTypeNoReceivedTimestampAsyncStatus `json:"asyncStatus"`

	// ID Id unique for this readout.
	ID string `json:"id"`

	// MessageTimestamp Timestamp when this message was created.
	MessageTimestamp time.Time `json:"messageTimestamp,omitzero"`

	// VehicleID The vehicle identifier of the extended vehicle, e.g VIN
	VehicleID string `json:"vehicleId"`
}

// CommonTypeNoReceivedTimestampAsyncStatus Reflects the status of the readouts
type CommonTypeNoReceivedTimestampAsyncStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// ErrorCode Error Code
	ErrorCode string `json:"errorCode,omitempty"`

	// ErrorMessage Error Message
	ErrorMessage string `json:"errorMessage,omitempty"`
}

// MaintenanceDataTable defines model for MaintenanceDataTable.
type MaintenanceDataTable = []MaintenanceTable

// ResourceDataContainer defines model for ResourceDataContainer.
type ResourceDataContainer struct {
	ResourceReadout *ResourceDataType `json:"resourceReadout,omitempty"`
}

// ResourceDataItem defines model for ResourceDataItem.
type ResourceDataItem struct {
	// API URI to API exposing resource
	API string `json:"api"`

	// Name Name of resource
	Name string `json:"name"`

	// Version Version of resource in API
	Version string `json:"version"`
}

// ResourceDataType defines model for ResourceDataType.
type ResourceDataType struct {
	// AsyncStatus Reflects the status of the readouts
	AsyncStatus ResourceDataTypeAsyncStatus `json:"asyncStatus"`

	// ID Id unique for this readout.
	ID string `json:"id"`

	// MessageTimestamp Timestamp when this message was created.
	MessageTimestamp time.Time `json:"messageTimestamp,omitzero"`

	// ReceivedTimestamp Timestamp when the data in the message was received by the ExVe backend from the vehicle.
	ReceivedTimestamp time.Time `json:"receivedTimestamp,omitempty,omitzero"`

	// Resources List of resources.
	Resources []ResourceDataItem `json:"resources,omitempty,omitzero"`

	// VehicleID The vehicle identifier of the extended vehicle, e.g VIN
	VehicleID string `json:"vehicleId"`
}

// ResourceDataTypeAsyncStatus Reflects the status of the readouts
type ResourceDataTypeAsyncStatus string

// ValueDataContainer defines model for ValueDataContainer.
type ValueDataContainer struct {
	ValueReadout *ValueDataType `json:"valueReadout,omitempty"`
}

// ValueDataItem defines model for ValueDataItem.
type ValueDataItem struct {
	// DistanceToService Distance to next service, only for PC and VAN
	DistanceToService string               `json:"distanceToService,omitempty"`
	MaintenanceData   MaintenanceDataTable `json:"maintenanceData,omitempty,omitzero"`

	// Odometervalue Odometer Value of the vehicle, only for PC and VAN
	Odometervalue string `json:"odometervalue,omitempty"`

	// Servicecode Servicecode of the vehicle, only for PC
	Servicecode string `json:"servicecode,omitempty"`

	// TimeToService Estimated time to next service, only for PC and VAN
	TimeToService string `json:"timeToService,omitempty"`

	// Workshopcode Version of resource in API
	Workshopcode string `json:"workshopcode,omitempty"`
}

// ValueDataType defines model for ValueDataType.
type ValueDataType struct {
	// AsyncStatus Reflects the status of the readouts
	AsyncStatus ValueDataTypeAsyncStatus `json:"asyncStatus"`

	// ID Id unique for this readout.
	ID string `json:"id"`

	// MaintenanceData List of values.
	MaintenanceData []ValueDataItem `json:"maintenanceData,omitempty,omitzero"`

	// MessageTimestamp Timestamp when this message was created.
	MessageTimestamp time.Time `json:"messageTimestamp,omitzero"`

	// ReceivedTimestamp Timestamp when the data in the message was received by the ExVe backend from the vehicle.
	ReceivedTimestamp time.Time `json:"receivedTimestamp,omitempty,omitzero"`

	// VehicleID The vehicle identifier of the extended vehicle, e.g VIN
	VehicleID string `json:"vehicleId"`
}

// ValueDataTypeAsyncStatus Reflects the status of the readouts
type ValueDataTypeAsyncStatus string

// VehicleDataReadoutRefreshDataContainer defines model for VehicleDataReadoutRefreshDataContainer.
type VehicleDataReadoutRefreshDataContainer struct {
	VehicleDataReadoutRefresh *VehicleDataReadoutRefreshDataType `json:"vehicleDataReadoutRefresh,omitempty"`
}

// VehicleDataReadoutRefreshDataItem defines model for VehicleDataReadoutRefreshDataItem.
type VehicleDataReadoutRefreshDataItem struct {
	// Message Specifies the exception message.
	Message string `json:"message"`
}

// VehicleDataReadoutRefreshDataType defines model for VehicleDataReadoutRefreshDataType.
type VehicleDataReadoutRefreshDataType struct {
	// AsyncStatus Reflects the status of the readouts
	AsyncStatus VehicleDataReadoutRefreshDataTypeAsyncStatus `json:"asyncStatus"`

	// ID Id unique for this readout.
	ID string `json:"id"`

	// Message Message of Vehicle Data Readout Refresh.
	Message []VehicleDataReadoutRefreshDataItem `json:"message,omitempty,omitzero"`

	// MessageTimestamp Timestamp when this message was created.
	MessageTimestamp time.Time `json:"messageTimestamp,omitzero"`

	// VehicleID The vehicle identifier of the extended vehicle, e.g VIN
	VehicleID string `json:"vehicleId"`
}

// VehicleDataReadoutRefreshDataTypeAsyncStatus Reflects the status of the readouts
type VehicleDataReadoutRefreshDataTypeAsyncStatus string

// MaintenanceLine defines model for maintenanceLine.
type MaintenanceLine struct {
	Data []struct {
		Name  string `json:"name,omitempty"`
		Type  string `json:"type,omitempty"`
		Value *struct {
			Doublevalue string `json:"doublevalue,omitempty"`
			Prefix      string `json:"prefix,omitempty"`
			Textvalue   string `json:"textvalue,omitempty"`
			Unit        string `json:"unit,omitempty"`
		} `json:"value,omitempty"`
	} `json:"data,omitempty,omitzero"`

	// Name Encoded text expression. To be resolved using VDC localizer textmessage service.
	Name string `json:"name,omitempty"`
	Type string `json:"type,omitempty"`
}

// MaintenanceTable defines model for maintenanceTable.
type MaintenanceTable struct {
	Line []MaintenanceLine `json:"line,omitempty,omitzero"`

	// Name Encoded text expression. To be resolved using VDC localizer textmessage service.
	Name string `json:"name,omitempty"`
	Type string `json:"type,omitempty"`
}

// WarningIndicatorReadoutDataContainer defines model for warningIndicatorReadoutDataContainer.
type WarningIndicatorReadoutDataContainer struct {
	MalfunctionIndicatorReadout *WarningIndicatorReadoutDataType `json:"malfunctionIndicatorReadout,omitempty"`
}

// WarningIndicatorReadoutDataItem defines model for warningIndicatorReadoutDataItem.
type WarningIndicatorReadoutDataItem struct {
	// FrequencyCounter How frequent this warning indicater has been recorded.
	FrequencyCounter string `json:"frequencyCounter,omitempty"`

	// Icon Base64 encoded icon file
	Icon string `json:"icon,omitempty"`

	// IgnitionCycleCounter How often the ignition has been started since first ocurrence.
	IgnitionCycleCounter string `json:"ignitionCycleCounter,omitempty"`

	// MostRecentOdometerValue Warning Indicator Readout most recent Odometer Value
	MostRecentOdometerValue string `json:"mostRecentOdometerValue,omitempty"`

	// OriginalOdometerValue Warning Indicator Readout Original Odometer Value
	OriginalOdometerValue string `json:"originalOdometerValue,omitempty"`

	// Status Warning Indicator Readout Status
	Status WarningIndicatorReadoutDataItemStatus `json:"status,omitempty"`

	// Text Contains Symptom and/or description text.
	Text *struct {
		// DescriptionText Description text of symptom
		DescriptionText string `json:"descriptionText,omitempty"`

		// SymptomText Text of Symptom
		SymptomText string `json:"symptomText,omitempty"`
	} `json:"text,omitempty"`
}

// WarningIndicatorReadoutDataItemStatus Warning Indicator Readout Status
type WarningIndicatorReadoutDataItemStatus string

// WarningIndicatorReadoutDataType defines model for warningIndicatorReadoutDataType.
type WarningIndicatorReadoutDataType struct {
	// AsyncStatus Reflects the status of the readouts
	AsyncStatus WarningIndicatorReadoutDataTypeAsyncStatus `json:"asyncStatus"`

	// ID Id unique for this readout.
	ID string `json:"id"`

	// MessageTimestamp Timestamp when this message was created.
	MessageTimestamp time.Time `json:"messageTimestamp,omitzero"`

	// ReceivedTimestamp Timestamp when the data in the message was received by the ExVe backend from the vehicle.
	ReceivedTimestamp time.Time `json:"receivedTimestamp,omitempty,omitzero"`

	// VehicleID The vehicle identifier of the extended vehicle, e.g VIN
	VehicleID string `json:"vehicleId"`

	// WarningIndicators Message of Vehicle Data Readout Refresh.
	WarningIndicators []WarningIndicatorReadoutDataItem `json:"warningIndicators,omitempty,omitzero"`
}

// WarningIndicatorReadoutDataTypeAsyncStatus Reflects the status of the readouts
type WarningIndicatorReadoutDataTypeAsyncStatus string
