// Package servicesv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package servicesv1

// Defines values for ConsentModel.
const (
	ConsentModelFleet        ConsentModel = "fleet"
	ConsentModelVehicleOwner ConsentModel = "vehicle_owner"
)

// Defines values for Role.
const (
	RoleBETA                         Role = "BETA"
	RoleFLEETCONSENTDOORLOCKUNLOCK   Role = "FLEET_CONSENT_DOOR_LOCK_UNLOCK"
	RoleFLEETCONSENTDRIVER           Role = "FLEET_CONSENT_DRIVER"
	RoleFLEETCONSENTIMMOBILIZER      Role = "FLEET_CONSENT_IMMOBILIZER"
	RoleFLEETCONSENTRESTRICTEDMARKET Role = "FLEET_CONSENT_RESTRICTED_MARKET"
	RoleFLEETCONSENTSTANDARD         Role = "FLEET_CONSENT_STANDARD"
	RoleVEHICLEOWNERCONSENTSTANDARD  Role = "VEHICLE_OWNER_CONSENT_STANDARD"
)

// Defines values for SignalDataType.
const (
	SignalDataTypeBoolean SignalDataType = "boolean"
	SignalDataTypeDouble  SignalDataType = "double"
	SignalDataTypeInt     SignalDataType = "int"
	SignalDataTypeString  SignalDataType = "string"
	SignalDataTypeUint16  SignalDataType = "uint16"
	SignalDataTypeUint32  SignalDataType = "uint32"
	SignalDataTypeUint8   SignalDataType = "uint8"
)

// Defines values for SignalSendingBehaviour.
const (
	SignalSendingBehaviourONCHANGE             SignalSendingBehaviour = "ON_CHANGE"
	SignalSendingBehaviourONCHARGINGCYCLE      SignalSendingBehaviour = "ON_CHARGING_CYCLE"
	SignalSendingBehaviourONCHARGINGCYCLEEND   SignalSendingBehaviour = "ON_CHARGING_CYCLE_END"
	SignalSendingBehaviourONCHARGINGDETECTION  SignalSendingBehaviour = "ON_CHARGING_DETECTION"
	SignalSendingBehaviourONCHARGINGSESSION    SignalSendingBehaviour = "ON_CHARGING_SESSION"
	SignalSendingBehaviourONCHARGINGSESSIONEND SignalSendingBehaviour = "ON_CHARGING_SESSION_END"
	SignalSendingBehaviourONIGNITIONLOCK       SignalSendingBehaviour = "ON_IGNITION_LOCK"
	SignalSendingBehaviourONINTERVAL120SEC     SignalSendingBehaviour = "ON_INTERVAL_120_SEC"
	SignalSendingBehaviourONINTERVAL15SEC      SignalSendingBehaviour = "ON_INTERVAL_15_SEC"
	SignalSendingBehaviourONINTERVAL30SEC      SignalSendingBehaviour = "ON_INTERVAL_30_SEC"
	SignalSendingBehaviourONRECHARGESESSION    SignalSendingBehaviour = "ON_RECHARGE_SESSION"
	SignalSendingBehaviourONREFRESH            SignalSendingBehaviour = "ON_REFRESH"
	SignalSendingBehaviourONREFUELINGEND       SignalSendingBehaviour = "ON_REFUELING_END"
	SignalSendingBehaviourONREFUELSESSION      SignalSendingBehaviour = "ON_REFUEL_SESSION"
	SignalSendingBehaviourONTRIP               SignalSendingBehaviour = "ON_TRIP"
	SignalSendingBehaviourONTRIPEND            SignalSendingBehaviour = "ON_TRIP_END"
)

// Defines values for SignalUnit.
const (
	SignalUnitDays          SignalUnit = "days"
	SignalUnitDegreeCelsius SignalUnit = "degree celsius"
	SignalUnitDegrees       SignalUnit = "degrees"
	SignalUnitKPa           SignalUnit = "kPa"
	SignalUnitKW            SignalUnit = "kW"
	SignalUnitKWh           SignalUnit = "kWh"
	SignalUnitKWh100Km      SignalUnit = "kWh/100km"
	SignalUnitKm            SignalUnit = "km"
	SignalUnitKmH           SignalUnit = "km/h"
	SignalUnitL100Km        SignalUnit = "l/100km"
	SignalUnitLiter         SignalUnit = "liter"
	SignalUnitMilliseconds  SignalUnit = "milliseconds"
	SignalUnitMin           SignalUnit = "min"
	SignalUnitPercent       SignalUnit = "percent"
	SignalUnitSeconds       SignalUnit = "seconds"
	SignalUnitV             SignalUnit = "V"
)

// Command defines model for Command.
type Command struct {
	// Mandatory Indicates if the command is mandatory for the generic service.
	Mandatory bool `json:"mandatory"`

	// Name The name of the command.
	Name string `json:"name"`
}

// ConsentModel The required consent model
type ConsentModel string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Detail details why this error occurred.
	Detail string `json:"detail,omitempty"`

	// Instance URI where this error occurred
	Instance string `json:"instance,omitempty"`

	// StatusCode status code of this error (e.g. http status code)
	StatusCode *int32 `json:"statusCode,omitempty"`

	// Title title of this error (e.g. http status reason phrase)
	Title string `json:"title,omitempty"`

	// Type URI-reference for type information or 'about:blank' if no more information is available
	Type string `json:"type,omitempty"`
}

// GetAllServicesResponse defines model for GetAllServicesResponse.
type GetAllServicesResponse struct {
	// Services The list of existing generic-services.
	Services []Service `json:"services,omitzero"`
}

// GetAllServicesWithSignalsAndCommandsResponse defines model for GetAllServicesWithSignalsAndCommandsResponse.
type GetAllServicesWithSignalsAndCommandsResponse struct {
	// Services The list of existing generic-services.
	Services []Service `json:"services,omitzero"`

	// Version The version of the services spec.
	Version string `json:"version,omitempty"`
}

// Role The list with required access roles
type Role string

// Service defines model for Service.
type Service struct {
	// CIAMScope The required CIAM scope
	CIAMScope string `json:"ciamScope"`

	// Commands The list of commands the generic-service consists of.
	Commands []Command `json:"commands,omitempty,omitzero"`

	// Consent The required consent model
	Consent ConsentModel `json:"consent"`

	// CountryCode The regional accessibility
	CountryCode string `json:"countryCode,omitempty"`

	// ID The id of the generic-service
	ID string `json:"id"`

	// Name The name of the generic-service.
	Name string `json:"name"`

	// Roles The list with required access roles
	Roles []Role `json:"roles,omitzero"`

	// Signals The list of signals the generic-service consists of.
	Signals []Signal `json:"signals,omitempty,omitzero"`
}

// Signal defines model for Signal.
type Signal struct {
	// DataType Describes the dataType of the signal.
	DataType SignalDataType `json:"dataType"`

	// Mandatory Indicates if the signal is mandatory for the generic-service.
	Mandatory bool `json:"mandatory"`

	// Name The name of the signal.
	Name string `json:"name"`

	// SendingBehaviour A list that describes the sending behaviour(s) of the signal in the PUSH-API context.
	SendingBehaviour []SignalSendingBehaviour `json:"sendingBehaviour,omitzero"`

	// Unit Describes the unit of the signal.
	Unit SignalUnit `json:"unit,omitempty"`
}

// SignalDataType Describes the dataType of the signal.
type SignalDataType string

// SignalSendingBehaviour Describes a sending behaviour of a signal in the PUSH-API context:
//   - *ON_CHANGE* - The signal is published as soon as its value changes and the delivery is technically possible.
//   - *ON_INTERVAL_120_SEC* - The signal is published at regular intervals of 120 seconds, if available.
//   - *ON_INTERVAL_30_SEC* - The signal is published at regular intervals of 30 seconds, if available.
//   - *ON_INTERVAL_15_SEC* - The signal is published at regular intervals of 15 seconds, if available.
//   - *ON_TRIP* - The signal is consumed (not published) during a trip for the purpose of aggregation at the end.
//   - *ON_TRIP_END* - The signal is published when the end of a trip is detected for a vehicle and all other trip-related signals have been received for said vehicle.
//   - *ON_CHARGING_SESSION* - The signal is consumed (not published) during a charging session for the purpose of aggregation at the end.
//   - *ON_CHARGING_SESSION_END* - The signal is published when the end of a charging session is detected for a vehicle and all other charging session related signals have been received for said vehicle.
//   - *ON_IGNITION_LOCK* - The signal is published when the ignition lock is detected for a vehicle.
//   - *ON_REFUEL_SESSION* - The signal is consumed (not published) during refueling of a vehicle with combustion engine for the purpose of aggregation.
//   - *ON_REFUELING_END* - The signal is published when the refueling of a vehicle with combustion engine has finished.
//   - *ON_CHARGING_CYCLE* - The signal is consumed (not published) during a charging cycle for the purpose of aggregation.
//   - *ON_CHARGING_CYCLE_END* - The signal is published when the end of a charging cycle is detected.
//   - *ON_RECHARGE_SESSION* - The signal is consumed (not published) during the battery charging process of an electrical or hybrid vehicle.
//   - *ON_CHARGING_DETECTION* - The signal is published as soon as the charging process of the battery of an electrical or hybrid vehicle has been active for a set duration.
//   - *ON_REFRESH* - The signal is published as soon as its value or timestamp changes and the delivery is technically possible.
type SignalSendingBehaviour string

// SignalUnit Describes the unit of the signal.
type SignalUnit string
