// Package vehiclespecificationfleetv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package vehiclespecificationfleetv1

// Defines values for Locales.
const (
	LocalesArOM Locales = "ar_OM"
	LocalesBgBG Locales = "bg_BG"
	LocalesCsCZ Locales = "cs_CZ"
	LocalesDaDK Locales = "da_DK"
	LocalesDeAT Locales = "de_AT"
	LocalesDeCH Locales = "de_CH"
	LocalesDeDE Locales = "de_DE"
	LocalesDeIT Locales = "de_IT"
	LocalesElGR Locales = "el_GR"
	LocalesEnAE Locales = "en_AE"
	LocalesEnBD Locales = "en_BD"
	LocalesEnBE Locales = "en_BE"
	LocalesEnBH Locales = "en_BH"
	LocalesEnCA Locales = "en_CA"
	LocalesEnDO Locales = "en_DO"
	LocalesEnDU Locales = "en_DU"
	LocalesEnEE Locales = "en_EE"
	LocalesEnFI Locales = "en_FI"
	LocalesEnGB Locales = "en_GB"
	LocalesEnID Locales = "en_ID"
	LocalesEnIE Locales = "en_IE"
	LocalesEnIL Locales = "en_IL"
	LocalesEnKR Locales = "en_KR"
	LocalesEnKW Locales = "en_KW"
	LocalesEnKZ Locales = "en_KZ"
	LocalesEnLK Locales = "en_LK"
	LocalesEnLT Locales = "en_LT"
	LocalesEnLV Locales = "en_LV"
	LocalesEnNL Locales = "en_NL"
	LocalesEnNO Locales = "en_NO"
	LocalesEnOM Locales = "en_OM"
	LocalesEnPH Locales = "en_PH"
	LocalesEnPL Locales = "en_PL"
	LocalesEnRO Locales = "en_RO"
	LocalesEnSL Locales = "en_SL"
	LocalesEnUS Locales = "en_US"
	LocalesEnXH Locales = "en_XH"
	LocalesEsCL Locales = "es_CL"
	LocalesEsCR Locales = "es_CR"
	LocalesEsDO Locales = "es_DO"
	LocalesEsES Locales = "es_ES"
	LocalesEsMX Locales = "es_MX"
	LocalesEsPA Locales = "es_PA"
	LocalesEsPY Locales = "es_PY"
	LocalesEtEE Locales = "et_EE"
	LocalesFiFI Locales = "fi_FI"
	LocalesFrCH Locales = "fr_CH"
	LocalesFrFR Locales = "fr_FR"
	LocalesFrMA Locales = "fr_MA"
	LocalesHeIL Locales = "he_IL"
	LocalesHrHR Locales = "hr_HR"
	LocalesHuHU Locales = "hu_HU"
	LocalesIsIS Locales = "is_IS"
	LocalesItCH Locales = "it_CH"
	LocalesItIT Locales = "it_IT"
	LocalesKoKR Locales = "ko_KR"
	LocalesLtLT Locales = "lt_LT"
	LocalesLvLV Locales = "lv_LV"
	LocalesNlNL Locales = "nl_NL"
	LocalesNoNO Locales = "no_NO"
	LocalesPlPL Locales = "pl_PL"
	LocalesRoRO Locales = "ro_RO"
	LocalesRuKZ Locales = "ru_KZ"
	LocalesSlSL Locales = "sl_SL"
	LocalesSrRS Locales = "sr_RS"
	LocalesSvSE Locales = "sv_SE"
	LocalesUkUA Locales = "uk_UA"
)

// Defines values for VehicleDataPoolflag.
const (
	VehicleDataPoolflagN VehicleDataPoolflag = "N"
	VehicleDataPoolflagP VehicleDataPoolflag = "P"
)

// Defines values for VehicleDataVehicleType.
const (
	VehicleDataVehicleTypeNEW  VehicleDataVehicleType = "NEW"
	VehicleDataVehicleTypeUSED VehicleDataVehicleType = "USED"
)

// CabinInfo defines model for CabinInfo.
type CabinInfo struct {
	// CabinBase Single equipment code information
	CabinBase *CodeText `json:"cabinBase,omitempty"`

	// CabinBottom Single equipment code information
	CabinBottom *CodeText `json:"cabinBottom,omitempty"`

	// CabinCombined Single equipment code information
	CabinCombined *CodeText `json:"cabinCombined,omitempty"`

	// CabinType Single equipment code information
	CabinType *CodeText `json:"cabinType,omitempty"`

	// CabinWidth Single equipment code information
	CabinWidth *CodeText `json:"cabinWidth,omitempty"`
}

// CodeText Single equipment code information
type CodeText struct {
	// Code equipment or package code
	Code string `json:"code,omitempty"`

	// Text standard code description
	Text string `json:"text,omitempty"`
}

// Emico defines model for Emico.
type Emico struct {
	ApprovedUsage    string `json:"approvedUsage,omitempty"`
	DriveConcept     string `json:"driveConcept,omitempty"`
	LegalContext     string `json:"legalContext,omitempty"`
	RawData          string `json:"rawData,omitempty"`
	RuleSetVersionID string `json:"ruleSetVersionID,omitempty"`
	TestProcedure    string `json:"testProcedure,omitempty"`
}

// Emission defines model for Emission.
type Emission struct {
	Combined  *float32 `json:"combined,omitempty"`
	Directive string   `json:"directive,omitempty"`
	In        *float32 `json:"in,omitempty"`
	Out       *float32 `json:"out,omitempty"`
}

// Engine defines model for Engine.
type Engine struct {
	Battery          *EngineBattery         `json:"battery,omitempty"`
	CylinderCapacity *int32                 `json:"cylinderCapacity,omitempty"`
	Emission         *EngineEmission        `json:"emission,omitempty"`
	FuelConsumption  *EngineFuelConsumption `json:"fuelConsumption,omitempty"`
	FuelTankCapacity *int32                 `json:"fuelTankCapacity,omitempty"`

	// FuelType Single equipment code information
	FuelType *CodeText    `json:"fuelType,omitempty"`
	Power    *EnginePower `json:"power,omitempty"`
	Range    *int32       `json:"range,omitempty"`
	Torque   *int32       `json:"torque,omitempty"`
}

// EngineBattery defines model for EngineBattery.
type EngineBattery struct {
	Capacity     *int32 `json:"capacity,omitempty"`
	ChargingTime *int32 `json:"chargingTime,omitempty"`
	Type         string `json:"type,omitempty"`
}

// EngineEmission defines model for EngineEmission.
type EngineEmission struct {
	City     *float32 `json:"city,omitempty"`
	Combined *float32 `json:"combined,omitempty"`
	Overland *float32 `json:"overland,omitempty"`
	Unit     string   `json:"unit,omitempty"`
}

// EngineFuelConsumption defines model for EngineFuelConsumption.
type EngineFuelConsumption struct {
	City     *float32 `json:"city,omitempty"`
	Combined *float32 `json:"combined,omitempty"`
	Overland *float32 `json:"overland,omitempty"`
	Unit     string   `json:"unit,omitempty"`
}

// EnginePower defines model for EnginePower.
type EnginePower struct {
	Kw *int32 `json:"kw,omitempty"`
	Ps *int32 `json:"ps,omitempty"`
}

// Error The error object contains detailed information about the error.
type Error struct {
	// ErrorMessage Error code message
	ErrorMessage string `json:"errorMessage,omitempty"`

	// Message Error detailed description
	Message string `json:"message,omitempty"`

	// StatusCode Error status code
	StatusCode string `json:"statusCode"`
}

// FuelConsumption defines model for FuelConsumption.
type FuelConsumption struct {
	Combined *float32 `json:"combined,omitempty"`
	In       *float32 `json:"in,omitempty"`
	Out      *float32 `json:"out,omitempty"`
}

// ImageID String representing the image id.
type ImageID = string

// LegacyEquipment defines model for LegacyEquipment.
type LegacyEquipment struct {
	Code        string `json:"code"`
	CodeType    string `json:"codeType,omitempty"`
	Description string `json:"description,omitempty"`
	Group       string `json:"group,omitempty"`
	Type        string `json:"type,omitempty"`
}

// Locales Market locale for country and language used for descriptions
// (ISO 3166 countries, ISO 639 languages).
type Locales string

// NewPrice defines model for NewPrice.
type NewPrice struct {
	Grossprice *float32 `json:"grossprice,omitempty"`
	Netprice   *float32 `json:"netprice,omitempty"`
	Tax        *float32 `json:"tax,omitempty"`
}

// OptionPackage defines model for OptionPackage.
type OptionPackage struct {
	Code    string            `json:"code,omitempty"`
	Options []LegacyEquipment `json:"options,omitempty,omitzero"`
	Text    string            `json:"text,omitempty"`
}

// PackageBasedOptions defines model for PackageBasedOptions.
type PackageBasedOptions struct {
	OptionPackages []OptionPackage   `json:"optionPackages,omitempty,omitzero"`
	Options        []LegacyEquipment `json:"options,omitempty,omitzero"`
}

// SalesDescription defines model for SalesDescription.
type SalesDescription struct {
	// Allwheel Single equipment code information
	Allwheel *CodeText `json:"allwheel,omitempty"`

	// Body Single equipment code information
	Body *CodeText `json:"body,omitempty"`

	// Extension Single equipment code information
	Extension *CodeText `json:"extension,omitempty"`

	// LengthType Single equipment code information
	LengthType *CodeText `json:"lengthType,omitempty"`

	// Line Single equipment code information
	Line *CodeText `json:"line,omitempty"`

	// Model Single equipment code information
	Model *CodeText `json:"model,omitempty"`

	// Style Single equipment code information
	Style *CodeText `json:"style,omitempty"`

	// Type Single equipment code information
	Type *CodeText `json:"type,omitempty"`
}

// TechnicalData defines model for TechnicalData.
type TechnicalData struct {
	ID    string `json:"id,omitempty"`
	Text  string `json:"text,omitempty"`
	Unit  string `json:"unit,omitempty"`
	Value string `json:"value,omitempty"`
}

// TypKey defines model for TypKey.
type TypKey struct {
	Hsn string `json:"hsn,omitempty"`
	Tsn string `json:"tsn,omitempty"`
	Vvs string `json:"vvs,omitempty"`
}

// VehicleData defines model for VehicleData.
type VehicleData struct {
	Allwheel  string `json:"allwheel,omitempty"`
	Baumuster string `json:"baumuster,omitempty"`

	// Body Single equipment code information
	Body   *CodeText `json:"body,omitempty"`
	Branch *int32    `json:"branch,omitempty"`

	// Brand Single equipment code information
	Brand *CodeText `json:"brand,omitempty"`

	// Cabin Single equipment code information
	Cabin            *CodeText  `json:"cabin,omitempty"`
	CabinInfo        *CabinInfo `json:"cabinInfo,omitempty"`
	Countrynumber    string     `json:"countrynumber,omitempty"`
	Cylindercapacity *int32     `json:"cylindercapacity,omitempty"`
	Emico            *Emico     `json:"emico,omitempty"`
	Emission         *Emission  `json:"emission,omitempty"`

	// Emissionstandard Single equipment code information
	Emissionstandard *CodeText `json:"emissionstandard,omitempty"`
	EngineCode       string    `json:"engineCode,omitempty"`

	// Enginetype Single equipment code information
	Enginetype *CodeText `json:"enginetype,omitempty"`
	Fin11      string    `json:"fin11,omitempty"`
	Finaldate  string    `json:"finaldate,omitempty"`

	// Fuel Single equipment code information
	Fuel            *CodeText        `json:"fuel,omitempty"`
	Fuelconsumption *FuelConsumption `json:"fuelconsumption,omitempty"`
	Function        string           `json:"function,omitempty"`
	Leather         string           `json:"leather,omitempty"`

	// Line Single equipment code information
	Line *CodeText `json:"line,omitempty"`

	// LongType National sales description of the vehicle
	LongType string `json:"longType,omitempty"`

	// LongTypeTechnical Language dependent technical vehicle type for Vans
	LongTypeTechnical string `json:"longTypeTechnical,omitempty"`
	Metallic          string `json:"metallic,omitempty"`
	Model             string `json:"model,omitempty"`
	ModelName         string `json:"modelName,omitempty"`
	ModelYear         string `json:"modelYear,omitempty"`
	ModelYearYear     string `json:"modelYearYear,omitempty"`

	// Modelrange Single equipment code information
	Modelrange          *CodeText            `json:"modelrange,omitempty"`
	Newprice            *NewPrice            `json:"newprice,omitempty"`
	Nst                 string               `json:"nst,omitempty"`
	Numberofdoors       *int32               `json:"numberofdoors,omitempty"`
	Numberofseats       *int32               `json:"numberofseats,omitempty"`
	Options             []LegacyEquipment    `json:"options,omitempty,omitzero"`
	PackageBasedOptions *PackageBasedOptions `json:"packageBasedOptions,omitempty"`
	Paint               *LegacyEquipment     `json:"paint,omitempty"`
	Paint2              *LegacyEquipment     `json:"paint2,omitempty"`
	Poolflag            VehicleDataPoolflag  `json:"poolflag,omitempty"`
	Powerkw             *int32               `json:"powerkw,omitempty"`
	Powerps             *int32               `json:"powerps,omitempty"`
	PrimaryEngine       *Engine              `json:"primaryEngine,omitempty"`

	// Productgroup Single equipment code information
	Productgroup     *CodeText         `json:"productgroup,omitempty"`
	SalesDescription *SalesDescription `json:"salesDescription,omitempty"`
	SecondaryEngine  *Engine           `json:"secondaryEngine,omitempty"`
	Shippingdate     string            `json:"shippingdate,omitempty"`
	ShortType        string            `json:"shortType,omitempty"`
	Status           string            `json:"status,omitempty"`

	// Subcategory Single equipment code information
	Subcategory *CodeText `json:"subcategory,omitempty"`

	// Suspensiontype Single equipment code information
	Suspensiontype *CodeText       `json:"suspensiontype,omitempty"`
	TechnicalData  []TechnicalData `json:"technicalData,omitempty,omitzero"`

	// Transmissiontype Single equipment code information
	Transmissiontype *CodeText              `json:"transmissiontype,omitempty"`
	Typeclass        string                 `json:"typeclass,omitempty"`
	Typekey          *TypKey                `json:"typekey,omitempty"`
	Upholstery       *LegacyEquipment       `json:"upholstery,omitempty"`
	VehicleType      VehicleDataVehicleType `json:"vehicleType,omitempty"`
	Vin11            string                 `json:"vin11,omitempty"`
	Weight           *Weight                `json:"weight,omitempty"`
	Wheelbase        *int32                 `json:"wheelbase,omitempty"`
	Wheelform        string                 `json:"wheelform,omitempty"`
}

// VehicleDataPoolflag defines model for VehicleData.Poolflag.
type VehicleDataPoolflag string

// VehicleDataVehicleType defines model for VehicleData.VehicleType.
type VehicleDataVehicleType string

// VehicleImagesResponse The response object contains the image ids of all available perspectives.
type VehicleImagesResponse struct {
	// EXT150 String representing the image id.
	EXT150 ImageID `json:"EXT150,omitempty"`

	// EXT330 String representing the image id.
	EXT330 ImageID `json:"EXT330,omitempty"`

	// INT1 String representing the image id.
	INT1 ImageID `json:"INT1,omitempty"`
}

// VehicleSpecificationResponse The response object contains the vehicle specification data of the
// requested vehicle and locale
type VehicleSpecificationResponse struct {
	VehicleData *VehicleData `json:"vehicleData,omitempty"`
}

// Weight defines model for Weight.
type Weight struct {
	Axis1         *int32 `json:"axis1,omitempty"`
	Axis2         *int32 `json:"axis2,omitempty"`
	Axis3         *int32 `json:"axis3,omitempty"`
	Axis4         *int32 `json:"axis4,omitempty"`
	Axis5         *int32 `json:"axis5,omitempty"`
	Axis6         *int32 `json:"axis6,omitempty"`
	Axislast      *int32 `json:"axislast,omitempty"`
	Extended      *int32 `json:"extended,omitempty"`
	Payload       *int   `json:"payload,omitempty"`
	Total         *int32 `json:"total,omitempty"`
	VehicleMassKg *int32 `json:"vehicleMassKg,omitempty"`
}
