Output cli.gif

Set FontSize 16
Set Width 1000
Set Height 1000
Set BorderRadius 10
Set WindowBar Colorful

Type "mbz"
Sleep 250ms
Enter
Sleep 5s
Ctrl+L
Sleep 25ms

Type "mbz auth login --region ECE"
Sleep 250ms
Enter
Type "client"
Enter
Type "secret"
Enter
Ctrl+L
Sleep 25ms

Type "mbz list-vehicles"
Sleep 250ms
Enter
Sleep 3s
Ctrl+L
Sleep 25ms

Type "mbz get-vehicle-services S0FTCARMB00000001"
Sleep 250ms
Enter
Sleep 3s
Ctrl+L
Sleep 25ms

Type "mbz auth logout"
Sleep 250ms
Enter
Sleep 1s
